%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-rmf-demos-tasks
Version:        1.2.0
Release:        4%{?dist}%{?release_suffix}
Summary:        ROS rmf_demos_tasks package

License:        Apache Licence 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-rolling-rmf-dispenser-msgs
Requires:       ros-rolling-rmf-fleet-msgs
Requires:       ros-rolling-rmf-lift-msgs
Requires:       ros-rolling-rmf-task-msgs
Requires:       ros-rolling-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-rolling-rmf-dispenser-msgs
BuildRequires:  ros-rolling-rmf-fleet-msgs
BuildRequires:  ros-rolling-rmf-lift-msgs
BuildRequires:  ros-rolling-rmf-task-msgs
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A package containing scripts for demos

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/rolling"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Mon Aug 16 2021 yadu <yadunund@openrobotics.org> - 1.2.0-4
- Autogenerated by Bloom

* Mon Aug 16 2021 yadu <yadunund@openrobotics.org> - 1.2.0-3
- Autogenerated by Bloom

* Mon Aug 16 2021 yadu <yadunund@openrobotics.org> - 1.2.0-2
- Autogenerated by Bloom

* Fri Jul 30 2021 yadu <yadunund@openrobotics.org> - 1.2.0-1
- Autogenerated by Bloom

